<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

In this lab you will use Python (with the NumPy library) to carry out linear algebra operations.

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [2]:
import numpy as np

In [4]:
a = [-12, 16]
b = [12, 9]

In [6]:
#answer:
np.dot(a,b)

0

2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [14]:
#answer:
np.multiply( a, b)

array([[ 5, 12],
       [21, 32]])

In [ ]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [28]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]

In [38]:
#answer:
result = [[0 for _ in range(3)] for _ in range(3)]

for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for row in result:
    print(row)

[13, 17, 34]
[31, 44, 91]
[49, 71, 148]


In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [42]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.

In [44]:
#answer:
result = [[0 for _ in range(4)] for _ in range(3)]

for i in range(len(X)):  
    for j in range(len(Y[0])):  
        for k in range(len(Y)):  
            result[i][j] += X[i][k] * Y[k][j]

for row in result:
    print(row)

[65, 72, 52, 80]
[59, 70, 112, 85]
[83, 80, 55, 99]


In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

Hint: Use
> np.linalg.det

In [48]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [50]:
#answer:
np.linalg.det(matrix)

17.999999999999996

6. Compute the inverse of an n x n matrix.

Hint: Use
> from numpy.linalg import inv

In [ ]:
a = np.array([[1., 2.], [3., 4.]])

In [52]:
#answer:
from numpy.linalg import inv
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

7. (Application)
Three customers made the following purchases of three different items at an office supply store:
* Customer W bought 2 notebooks, 4 pens and 3 staplers for \$38.80
* Customer X bought 3 notebooks, 3 pens and 2 staplers for \$32.00
* Customer Y bought 4 notebooks, 8 pens and 1 stapler for \$36.60

Based on this, how much did customer Z spend in buying 1 notebook, 2 pens and 4 staplers?

In [58]:
# answer
items = np.array([[2, 4, 3], 
              [3, 3, 2],
              [4, 8, 1]])

cost = np.array([38.80, 32.00, 36.60])

perunit = np.linalg.solve(items, cost)
print(perunit)

[3.3 1.9 8.2]


In [74]:
Z = (1 * perunit[0]) + (2 * perunit[1]) + (4 * perunit[2])
print('Customer Z spent $',Z)

Customer Z spent $ 39.9




---



---



> > > > > > > > > © 2025 Institute of Data


---



---



