<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

In Lab 4.1.1 we were able to predict house price via a predictor variable from first principles. Here we the see how the same can be done using scikit-learn.

For comparison purposes, we will continue with the same predictor `sq__ft` in our dataset as last time.

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [89]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Read in the data

In [15]:
# Read CSV
house_csv = r"C:\Users\ryant\Desktop\IOD\DATA\Sacramento_transactions.csv"
data = pd.read_csv(house_csv)
data

street             city    zip state  beds  baths  sq__ft  \
0           3526 HIGH ST       SACRAMENTO  95838    CA     2      1     836   
1            51 OMAHA CT       SACRAMENTO  95823    CA     3      1    1167   
2         2796 BRANCH ST       SACRAMENTO  95815    CA     2      1     796   
3       2805 JANETTE WAY       SACRAMENTO  95815    CA     2      1     852   
4        6001 MCMAHON DR       SACRAMENTO  95824    CA     2      1     797   
..                   ...              ...    ...   ...   ...    ...     ...   
980   9169 GARLINGTON CT       SACRAMENTO  95829    CA     4      3    2280   
981      6932 RUSKUT WAY       SACRAMENTO  95823    CA     3      2    1477   
982    7933 DAFFODIL WAY   CITRUS HEIGHTS  95610    CA     3      2    1216   
983     8304 RED FOX WAY        ELK GROVE  95758    CA     4      2    1685   
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762    CA     3      2    1362   

            type                     sale_date   price   latitude   longitude  
0    Residential  Wed May 21 00:00:00 EDT 2008   59222  38.631913 -121.434879  
1    Residential  Wed May 21 00:00:00 EDT 2008   68212  38.478902 -121.431028  
2    Residential  Wed May 21 00:00:00 EDT 2008   68880  38.618305 -121.443839  
3    Residential  Wed May 21 00:00:00 EDT 2008   69307  38.616835 -121.439146  
4    Residential  Wed May 21 00:00:00 EDT 2008   81900  38.519470 -121.435768  
..           ...                           ...     ...        ...         ...  
980  Residential  Thu May 15 00:00:00 EDT 2008  232425  38.457679 -121.359620  
981  Residential  Thu May 15 00:00:00 EDT 2008  234000  38.499893 -121.458890  
982  Residential  Thu May 15 00:00:00 EDT 2008  235000  38.708824 -121.256803  
983  Residential  Thu May 15 00:00:00 EDT 2008  235301  38.417000 -121.397424  
984  Residential  Thu May 15 00:00:00 EDT 2008  235738  38.655245 -121.075915  

[985 rows x 12 columns]

### 2. Predict Price

We are going to predict the target variable `price` from `sq__ft` using sklearn's linear_model.

Read up on the following methods and attributes here: [sklearn.linear_model.LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

- coef_
- intercept_
- fit()
- predict()
- score()

#### 2.1 Create an instance of LinearRegression.

In [30]:
# ANSWER
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()

#### 2.2 Fit predictor and target variables using linear regression

In [34]:
X = data['sq__ft'].values.reshape(-1,1)
y = data['price']

In [60]:
print(X.shape, y.shape)

(985, 1) (985,)


In [41]:
# ANSWER
linreg.fit(X , y)

LinearRegression()

#### 2.3. Using attributes of the LinearRegression() class find coefficient and intercept.

In [44]:
# ANSWER
print('Coefficient = ',linreg.coef_)
print('Intercept = ',linreg.intercept_)


Coefficient =  [54.15863969]
Intercept =  162930.1614069977


#### 2.4 Find R^2 Score

Find $R^2$ Using the ```score``` method of LinearRegression.

In [48]:
# ANSWER
linreg.score(X , y)

0.11148717682951459

### 3. Splitting Data


Splitting the data into training and test sets is important in supervised learning.

- We ensure that the test set remains untouched during the model training process. This isolation prevents any information leakage about the test set into the training process.

- It allows us to evaluate the performance of our machine learning model on unseen data.


In [50]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Use the `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [52]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [80]:
# ANSWER
## Check training/test data
print('Xtrain =', X_train.shape, '\n'
      'Xtest  =', X_test.shape, '\n'
      'ytrain =', y_train.shape, '\n'
      'ytest  =', y_test.shape)

Xtrain = (659, 1) 
Xtest  = (326, 1) 
ytrain = (659,) 
ytest  = (326,)


In [148]:
print('Sample of Xtrain:\n',
      X_train[:10])
print('')
print('Sample of Xtest:\n',
      X_test[:10])
print('')
print('Sample of ytrain:\n',
      y_train[:10])
print('')
print('Sample of ytest:\n',
      y_test[:10])

Sample of Xtrain:
 [[1758]
 [1643]
 [2354]
 [   0]
 [1354]
 [   0]
 [ 958]
 [1232]
 [ 888]
 [1440]]

Sample of Xtest:
 [[ 906]
 [2382]
 [1962]
 [1739]
 [1527]
 [   0]
 [   0]
 [1900]
 [   0]
 [   0]]

Sample of ytrain:
 433    217500
172     99000
125    335750
541    488750
879    104000
888    119000
90     244960
924    170000
181    125000
274    292000
Name: price, dtype: int64

Sample of ytest:
 613     77000
451    236000
731    240971
436    221000
275    293993
582      4897
707    215000
299    361745
718    222500
494    307000
Name: price, dtype: int64


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [151]:
# ANSWER
linreg.fit(X_train, y_train)

LinearRegression()

In [153]:
# ANSWER
linreg.score(X_test, y_test)

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using the linear regression model.**

In [159]:
# ANSWER
print(linreg.coef_ , linreg.intercept_)

[47.43508406] 166482.34144968854


In [197]:
predy = [[1204]]
print('Predicted house price',linreg.predict(predy))

Predicted house price [223594.18266381]


#### Find the mean squared error

In [207]:
# Predict prices from X_test, then compare with y_test to find the mean squared error
y_pred = linreg.predict(X_test)
y_pred[:20]

array([209458.52761247, 279472.71169224, 259549.97638499, 248971.95263852,
       238915.71481676, 166482.34144969, 166482.34144969, 256609.00117297,
       166482.34144969, 166482.34144969, 217807.10240789, 166482.34144969,
       220558.33728366, 166482.34144969, 219040.41459358, 241714.38477659,
       204193.23328127, 204240.66836534, 166482.34144969, 309214.50940092])

In [221]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_test, y_pred)

137665.54386542056

### Conclusion
We have seen that through scikit-learn, minimal code is needed to implement and evaluate a linear regression model.



---



---



> > > > > > > > > © 2024 Institute of Data


---



---



